#!/usr/bin/env node
"use strict";

const http          = require("http");
const fs            = require("fs");
const path          = require("path");
const os            = require("os");
const { spawnSync } = require("child_process");

const PORT      = 9400;
const REPO_ROOT = path.resolve(__dirname, "..", "..", "..");
const STORIES_REL = path.join("apps", "storybook", "stories", "generated");

const CORS = {
  "Access-Control-Allow-Origin":  "*",
  "Access-Control-Allow-Methods": "POST, GET, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

// ── Component registry ────────────────────────────────────────────────────────

const REGISTRY = [
  {
    pattern: /button/i,
    name: "Button",
    render: () => `<button class="c-button c-button--primary" type="button">Get started</button>`,
  },
  {
    pattern: /icon.?button|btn.*icon/i,
    name: "IconButton",
    render: () => `<button class="c-icon-button" type="button" aria-label="Action"></button>`,
  },
  {
    pattern: /product.?lockup|app.?lockup/i,
    name: "ProductLockup",
    render: () => `<div class="c-product-lockup"><!-- ProductLockup --></div>`,
  },
  {
    pattern: /nav.?card|router.?marquee/i,
    name: "NavCard",
    render: () => `<div class="c-nav-card"><!-- NavCard --></div>`,
  },
  {
    pattern: /heading|title|eyebrow|h1|h2|h3/i,
    name: "Heading",
    render: (node) => `<h2 class="c-heading">${node.name || "Heading"}</h2>`,
  },
  {
    pattern: /body|paragraph|text|copy|rich.?content/i,
    name: "Body",
    render: () => `<p class="c-body">Body copy</p>`,
  },
  {
    pattern: /media|image|img|video|background/i,
    name: "Media",
    render: () => `<div class="c-media" style="aspect-ratio:16/9;background:var(--s2a-color-background-disabled);"><!-- Media --></div>`,
  },
  {
    pattern: /elastic.?card|card/i,
    name: "Card",
    render: () => `<div class="c-elastic-card"><!-- Card --></div>`,
  },
];

// ── Helpers ───────────────────────────────────────────────────────────────────

function toSlug(name) {
  return name.replace(/[^a-zA-Z0-9\s-]/g, "").replace(/\s+/g, "-").toLowerCase();
}

function toPascal(name) {
  return name
    .replace(/[^a-zA-Z0-9\s]/g, " ")
    .split(/\s+/)
    .filter(Boolean)
    .map(w => w[0].toUpperCase() + w.slice(1).toLowerCase())
    .join("");
}

function detectComponents(selection) {
  const detected = [];
  const unmapped = [];
  const candidates = [
    ...(selection.children || []),
    ...(selection.children || []).flatMap(c => c.children || []),
  ];
  for (const node of candidates) {
    if (!node.name) continue;
    const match = REGISTRY.find(r => r.pattern.test(node.name));
    if (match) {
      if (!detected.find(d => d.name === match.name)) detected.push({ ...match, node });
    } else if (!["TEXT", "VECTOR", "LINE"].includes(node.type)) {
      unmapped.push(node.name);
    }
  }
  return { detected, unmapped: [...new Set(unmapped)].slice(0, 8) };
}

function generateStoryFile({ selection, prompt, frameName, componentName, slug }) {
  const { detected, unmapped } = detectComponents(selection);
  const date = new Date().toISOString().split("T")[0];
  const mappedComponents = detected.length
    ? detected.map(d => `      ${d.render(d.node)}`).join("\n")
    : `      <!-- TODO: map layers from "${frameName}" to S2A components -->`;
  const mappingReport = [
    detected.length ? `Mapped: ${detected.map(d => d.name).join(", ")}` : "No components auto-mapped.",
    unmapped.length ? `Unmapped layers: ${unmapped.join(", ")}` : "",
  ].filter(Boolean).join(" · ");
  const promptNote  = prompt ? `\n * Intent: ${prompt}` : "";
  const unmappedNote = unmapped.length ? `\n * ⚠ Unmapped: ${unmapped.join(", ")}` : "";

  return `import { html } from "lit";

/**
 * ${frameName}
 * Generated by S2A Toolkit · ${date}
 * Source: ${selection.fileName || "Figma"} — ${selection.page?.name || ""}${promptNote}${unmappedNote}
 *
 * ${mappingReport}
 */

export default {
  title: "Prototypes/Generated/${componentName}",
  tags: ["prototype", "generated-from-figma", "autodocs"],
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component: \`Prototype generated from Figma frame **${frameName}**.\\n\\n${mappingReport.replace(/\`/g, "'")}\\n\\nReview token usage and component mapping before promoting to production.\`,
      },
    },
  },
};

const template = () => html\`
  <div
    class="c-prototype c-prototype--${slug}"
    style="padding:var(--s2a-spacing-lg);background:var(--s2a-color-background-inverse);"
  >
${mappedComponents}
  </div>
\`;

export const Default = { render: template };

export const Desktop = {
  parameters: { viewport: { defaultViewport: "desktop" } },
  render: template,
};

export const Mobile = {
  parameters: { viewport: { defaultViewport: "mobile1" } },
  render: template,
};
`;
}

function buildPRBody({ frameName, selection, prompt, storyFileRelative, checks, branchName }) {
  const c = (ok, label) => (ok ? "✓" : "⚠") + " " + label;
  return `## Generated from Figma

| | |
|---|---|
| **Source file** | ${selection.fileName || "—"} |
| **Frame** | ${frameName} |
| **Page** | ${selection.page?.name || "—"} |
| **Generated by** | S2A Toolkit |
${prompt ? `| **Intent** | ${prompt} |\n` : ""}
## What changed

- Added \`${storyFileRelative}\`
- Branch: \`${branchName}\`

## Validation

- ${c(checks.lint, "Lint")}
- ${c(checks.typecheck, "Typecheck")}
- ⏳ Storybook build (CI)

## Notes

This PR is a **prototype review artifact**. Labels: \`prototype\`, \`generated-from-figma\`.
Review component mapping and token usage before promoting to production.

---
🤖 Generated with [S2A Toolkit](https://github.com/adobecom/consonant)`;
}

// ── Git helpers ───────────────────────────────────────────────────────────────

function git(args) {
  const r = spawnSync("git", args, { cwd: REPO_ROOT, encoding: "utf8", timeout: 30000 });
  return { ok: r.status === 0, stdout: r.stdout.trim(), stderr: r.stderr.trim() };
}

function makeWorktreeGit(worktreeDir) {
  return function(args) {
    const r = spawnSync("git", args, { cwd: worktreeDir, encoding: "utf8", timeout: 30000 });
    return { ok: r.status === 0, stdout: r.stdout.trim(), stderr: r.stderr.trim() };
  };
}

function listPrototypeBranches() {
  const current = git(["branch", "--show-current"]).stdout;
  const all = git(["branch", "-a", "--format=%(refname:short)"]).stdout.split("\n").filter(Boolean);
  const proto = [...new Set(
    all.map(b => b.replace(/^origin\//, "")).filter(b => b.startsWith("figma-prototype/"))
  )].sort().reverse();
  return { current, prototypeBranches: proto };
}

// ── Core generator (worktree — never switches the main working dir branch) ────

function generatePrototype({ selection, prompt, branchOverride }) {
  const frameName = (selection.name || "Untitled").trim();
  const slug      = toSlug(frameName);
  const pascal    = toPascal(frameName);
  const date      = new Date().toISOString().split("T")[0];
  const branch    = (branchOverride || `figma-prototype/${slug}-${date}`).trim();
  const fileName  = `${pascal}.stories.js`;
  const relPath   = path.join(STORIES_REL, fileName);

  // Ensure remote refs are fresh
  git(["fetch", "origin", "main"]);

  // Determine whether to use a worktree or work in REPO_ROOT directly.
  // A branch already checked out in REPO_ROOT cannot have a second worktree.
  const currentBranch = git(["branch", "--show-current"]).stdout;
  const localExists   = git(["branch", "--list", branch]).stdout.length > 0;
  const remoteExists  = git(["branch", "-r", "--list", `origin/${branch}`]).stdout.length > 0;
  const isCurrentBranch = currentBranch === branch;

  const worktreeDir = isCurrentBranch
    ? null
    : path.join(os.tmpdir(), `s2a-worktree-${slug}-${Date.now()}`);

  if (!isCurrentBranch) {
    let wtResult;
    if (localExists) {
      wtResult = git(["worktree", "add", worktreeDir, branch]);
    } else if (remoteExists) {
      wtResult = git(["worktree", "add", "--track", "-b", branch, worktreeDir, `origin/${branch}`]);
    } else {
      wtResult = git(["worktree", "add", "-b", branch, worktreeDir, "origin/main"]);
    }
    if (!wtResult.ok) throw new Error("Worktree setup failed: " + wtResult.stderr);
  }

  const baseDir = worktreeDir || REPO_ROOT;
  const wgit = worktreeDir ? makeWorktreeGit(worktreeDir) : git;

  try {
    const content = generateStoryFile({ selection, prompt, frameName, componentName: pascal, slug });

    // Always write to STORIES_OUT in the current checkout so Storybook hot-reloads it
    const liveStoryDir = path.join(REPO_ROOT, STORIES_REL);
    const liveAbsPath  = path.join(liveStoryDir, fileName);
    fs.mkdirSync(liveStoryDir, { recursive: true });
    fs.writeFileSync(liveAbsPath, content, "utf8");
    console.log(`[proto]  wrote ${relPath} to live checkout (Storybook preview)`);

    // Also write to the worktree (or same dir if on that branch) for git commit
    const storyDir = path.join(baseDir, STORIES_REL);
    const absPath  = path.join(storyDir, fileName);
    if (baseDir !== REPO_ROOT) {
      fs.mkdirSync(storyDir, { recursive: true });
      fs.writeFileSync(absPath, content, "utf8");
    }
    console.log(`[proto]  wrote ${relPath}  (branch: ${branch})`);

    // Checks (non-blocking)
    const lint      = spawnSync("npm", ["run", "lint",      "--if-present"], { cwd: REPO_ROOT, encoding: "utf8", timeout: 60000 });
    const typecheck = spawnSync("npm", ["run", "typecheck", "--if-present"], { cwd: REPO_ROOT, encoding: "utf8", timeout: 60000 });
    const checks    = { lint: lint.status === 0, typecheck: typecheck.status === 0 };
    console.log(`[proto]  lint=${checks.lint} typecheck=${checks.typecheck}`);

    // Commit (skip if story is identical to last commit)
    wgit(["add", absPath]);
    const staged = wgit(["diff", "--cached", "--name-only"]);
    if (staged.stdout.trim().length > 0) {
      const msg = `feat(prototype): generate ${frameName} from Figma\n\nSource: ${selection.fileName || "Figma"}\nFrame: ${frameName}`;
      const commit = wgit(["commit", "-m", msg]);
      if (!commit.ok) throw new Error("Commit failed: " + (commit.stderr || commit.stdout));
    } else {
      console.log(`[proto]  no changes — story unchanged, skipping commit`);
    }

    // Push
    const push = wgit(["push", "-u", "origin", branch]);
    if (!push.ok) throw new Error("Push failed: " + push.stderr);

    // PR — reuse existing if already open for this branch
    const existingPR = spawnSync("gh", ["pr", "view", branch, "--json", "url", "--jq", ".url"],
      { cwd: REPO_ROOT, encoding: "utf8", timeout: 15000 });
    let prUrl = existingPR.status === 0 ? existingPR.stdout.trim() : null;

    if (!prUrl) {
      const prBody = buildPRBody({ frameName, selection, prompt, storyFileRelative: relPath, checks, branchName: branch });
      const pr = spawnSync(
        "gh",
        ["pr", "create", "--title", `prototype: ${frameName}`, "--body", prBody, "--draft", "--label", "prototype"],
        { cwd: REPO_ROOT, encoding: "utf8", timeout: 30000 }
      );
      prUrl = pr.status === 0 ? pr.stdout.trim() : null;
      if (!prUrl) console.warn("[proto]  PR creation failed:", pr.stderr);
    }

    return { storyFile: relPath, branchName: branch, prUrl, checks };
  } finally {
    if (worktreeDir) git(["worktree", "remove", "--force", worktreeDir]);
  }
}

// ── HTTP server ───────────────────────────────────────────────────────────────

const server = http.createServer((req, res) => {
  if (req.method === "OPTIONS") {
    res.writeHead(204, CORS);
    res.end();
    return;
  }

  if (req.method === "GET" && req.url === "/open-cursor") {
    spawnSync("open", ["-a", "Cursor", REPO_ROOT]);
    res.writeHead(200, { ...CORS, "Content-Type": "application/json" });
    res.end(JSON.stringify({ ok: true, path: REPO_ROOT }));
    return;
  }

  if (req.method === "GET" && req.url === "/health") {
    res.writeHead(200, { ...CORS, "Content-Type": "application/json" });
    res.end(JSON.stringify({ ok: true, port: PORT, version: "0.2.0" }));
    return;
  }

  if (req.method === "GET" && req.url === "/open-cursor") {
    spawnSync("open", ["-a", "Cursor", REPO_ROOT]);
    res.writeHead(200, { ...CORS, "Content-Type": "application/json" });
    res.end(JSON.stringify({ ok: true, path: REPO_ROOT }));
    return;
  }

  if (req.method === "GET" && req.url === "/git/branches") {
    try {
      const data = listPrototypeBranches();
      res.writeHead(200, { ...CORS, "Content-Type": "application/json" });
      res.end(JSON.stringify({ ok: true, ...data }));
    } catch (err) {
      res.writeHead(500, { ...CORS, "Content-Type": "application/json" });
      res.end(JSON.stringify({ error: err.message }));
    }
    return;
  }

  if (req.method === "POST" && req.url === "/prototype/generate") {
    let body = "";
    req.on("data", chunk => { body += chunk; });
    req.on("end", () => {
      let selection, prompt, branch;
      try {
        ({ selection, prompt, branch } = JSON.parse(body));
      } catch {
        res.writeHead(400, { ...CORS, "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: "Invalid JSON body" }));
        return;
      }

      if (!selection?.name) {
        res.writeHead(400, { ...CORS, "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: "Missing selection.name — select a frame first" }));
        return;
      }

      console.log(`[proto]  generating: "${selection.name}" → ${branch || "(auto branch)"}`);
      try {
        const result = generatePrototype({
          selection,
          prompt: (prompt || "").trim(),
          branchOverride: branch || null,
        });
        res.writeHead(200, { ...CORS, "Content-Type": "application/json" });
        res.end(JSON.stringify({ ok: true, ...result }));
      } catch (err) {
        console.error("[proto]  error:", err.message);
        res.writeHead(500, { ...CORS, "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: err.message || "Generation failed" }));
      }
    });
    return;
  }

  res.writeHead(404, CORS);
  res.end();
});

server.listen(PORT, "localhost", () => {
  console.log(`\n[S2A Prototype Server] http://localhost:${PORT}`);
  console.log(`  POST /prototype/generate  — Figma selection + prompt + branch → story + PR`);
  console.log(`  GET  /git/branches        — list current + prototype branches`);
  console.log(`  GET  /open-cursor         — open repo in Cursor`);
  console.log(`  GET  /health              — health check\n`);
});
