import { AnalyticsDashboard } from "./AnalyticsDashboard";

export default {
  title: "Foundations/Analytics Dashboard",
  tags: ["autodocs"],
  render: () => AnalyticsDashboard(),
  parameters: {
    layout: "fullscreen",
    docs: {
      description: {
        component: `<p>Live S2A design system health — Figma Library Analytics (adoption trend, deprecated-vs-current usage, top consuming teams) plus a token-compliance audit of what's actually shipping in Milo. Data is generated by <code>apps/storybook/scripts/generate-analytics-snapshot.js</code> and regenerated automatically on every Storybook dev/build run.</p>`,
      },
    },
  },
};

export const Default = {};
