#!/usr/bin/env node
/**
 * token-release / prepare-release.js <version> <bump>
 * -----------------------------------------------------------------------
 * Run after `version.js <bump>` has already bumped packages/tokens/package.json.
 * Diffs the freshly-built dist CSS against what's still committed at HEAD
 * (i.e. the pre-release state — we haven't committed yet), writes a
 * CHANGELOG.md entry, and writes a PR body + diff summary for the workflow
 * to use in later steps.
 *
 * Outputs:
 *   packages/tokens/CHANGELOG.md  — new [version] section prepended
 *   .github/scripts/token-release/.pr-body.md   — PR body (gitignored)
 *   .github/scripts/token-release/.diff-summary.json  — { added, removed, changed }
 */
const fs = require("fs");
const path = require("path");
const { execFileSync } = require("child_process");

const ROOT = path.resolve(__dirname, "..", "..", "..");
const DIST_CSS_REL = path.join("dist", "packages", "tokens", "css", "dev");
const CHANGELOG_PATH = path.join(ROOT, "packages", "tokens", "CHANGELOG.md");
const SCRIPT_DIR = __dirname;

const [version, bump] = process.argv.slice(2);
if (!version) {
  console.error("Usage: node prepare-release.js <version> <bump>");
  process.exit(1);
}

function sh(args) {
  try {
    return execFileSync("git", args, { cwd: ROOT, encoding: "utf8" });
  } catch {
    return "";
  }
}

function extractVars(css) {
  const map = new Map();
  for (const m of css.matchAll(/(--s2a-[\w-]+)\s*:\s*([^;]+);/g)) {
    map.set(m[1], m[2].trim());
  }
  return map;
}

function diffTokens() {
  const cssDevDir = path.join(ROOT, DIST_CSS_REL);
  const files = fs.existsSync(cssDevDir) ? fs.readdirSync(cssDevDir).filter(f => f.endsWith(".css")) : [];

  const oldVars = new Map();
  const newVars = new Map();

  for (const file of files) {
    const newCss = fs.readFileSync(path.join(cssDevDir, file), "utf8");
    for (const [k, v] of extractVars(newCss)) newVars.set(k, v);

    const gitPath = path.join(DIST_CSS_REL, file).split(path.sep).join("/");
    const oldCss = sh(["show", `HEAD:${gitPath}`]);
    if (oldCss) {
      for (const [k, v] of extractVars(oldCss)) oldVars.set(k, v);
    }
  }

  const added = [...newVars.keys()].filter(k => !oldVars.has(k)).sort();
  const removed = [...oldVars.keys()].filter(k => !newVars.has(k)).sort();
  const changed = [...newVars.keys()].filter(k => oldVars.has(k) && oldVars.get(k) !== newVars.get(k)).sort();

  return { added, removed, changed, oldVars, newVars };
}

function buildChangelogEntry(diff) {
  const date = new Date().toISOString().slice(0, 10);
  const lines = [`## [${version}] - ${date}`, "", "_Auto-generated by the token release pipeline — verify before merge._", ""];

  if (diff.added.length) {
    lines.push("### ✨ Added", "");
    for (const name of diff.added) lines.push(`- \`${name}: ${diff.newVars.get(name)}\``);
    lines.push("");
  }
  if (diff.removed.length) {
    lines.push("### 💥 Removed", "");
    for (const name of diff.removed) lines.push(`- \`${name}\` (was \`${diff.oldVars.get(name)}\`)`);
    lines.push("");
  }
  if (diff.changed.length) {
    lines.push("### ♻️ Changed", "");
    for (const name of diff.changed) lines.push(`- \`${name}\`: \`${diff.oldVars.get(name)}\` → \`${diff.newVars.get(name)}\``);
    lines.push("");
  }
  if (!diff.added.length && !diff.removed.length && !diff.changed.length) {
    lines.push("_No CSS custom property changes detected._", "");
  }

  return lines.join("\n");
}

function buildPRBody(diff) {
  return `## Token release: ${version}

| | |
|---|---|
| **Bump** | ${bump || "patch"} |
| **Source** | Figma (main file) |

## Token diff

- ✨ Added: ${diff.added.length}
- 💥 Removed: ${diff.removed.length}
- ♻️ Changed: ${diff.changed.length}

## Checklist (from token-release skill)

- [ ] No primitive token names declared directly in semantic/responsive output
- [ ] Responsive files contain only breakpoint-specific overrides
- [ ] CHANGELOG.md entry reads clearly (auto-generated — polish wording if needed)

---
🤖 Generated by the [S2A token release workflow](../../actions/workflows/token-release.yml)`;
}

const diff = diffTokens();

const existingChangelog = fs.readFileSync(CHANGELOG_PATH, "utf8");
const headerEnd = existingChangelog.indexOf("\n## [");
const preamble = headerEnd === -1 ? existingChangelog.trimEnd() + "\n\n" : existingChangelog.slice(0, headerEnd + 1);
const rest = headerEnd === -1 ? "" : existingChangelog.slice(headerEnd + 1);
fs.writeFileSync(CHANGELOG_PATH, preamble + buildChangelogEntry(diff) + "\n" + rest, "utf8");

fs.writeFileSync(path.join(SCRIPT_DIR, ".pr-body.md"), buildPRBody(diff), "utf8");
fs.writeFileSync(
  path.join(SCRIPT_DIR, ".diff-summary.json"),
  JSON.stringify({ added: diff.added.length, removed: diff.removed.length, changed: diff.changed.length }, null, 2),
  "utf8"
);

console.log(`✓ CHANGELOG.md updated for ${version}`);
console.log(`  added=${diff.added.length} removed=${diff.removed.length} changed=${diff.changed.length}`);
