// <slug>.spec.md — the contract as a readable page: props, states, anatomy
// with resolved tokens, slots, decisions, accessibility, provenance.
const cell = (v) => String(v ?? "—").replace(/\|/g, "\\|").replace(/\n/g, " ");
const fig = (b) => (b === "NONE" ? "NONE" : `${b.kind} \`${b.property}\`${b.verified === false ? " (not in evidence)" : b.verified ? " ✓" : ""}`);

export function markdown(ir) {
  const L = [];
  L.push(`<!-- Generated by ${ir.generator.name}@${ir.generator.version}; do not edit. Source: ${ir.component.slug}.defs.json + evidence. -->`);
  L.push(`# ${ir.component.name}`, "");
  if (ir.component.description) L.push(ir.component.description, "");
  L.push(`Status: **${ir.component.status}** · root \`${ir.component.cssClass}\` · import \`${ir.anchors.code.importPath}\` → \`${ir.anchors.code.export}\`${ir.anchors.code.controller ? ` (+ \`${ir.anchors.code.controller}\`)` : ""}`, "");
  L.push("## Anchors", "", "| Side | Where | Notes |", "| --- | --- | --- |");
  const f = ir.anchors.figma;
  L.push(`| Figma | ${f.kind} \`${f.nodeId ?? "?"}\` ${cell(f.nodeName)}${f.deprecated ? " (deprecated)" : ""} | ${ir.figmaEvidence ? `evidence ${ir.figmaEvidence.hash}` : "no plugin evidence published yet"}; used by ${f.usages.length ? f.usages.map((u) => `\`${u}\``).join(", ") : "—"} |`);
  L.push(`| Code | \`${ir.anchors.code.importPath}\` | ${ir.code ? `render \`${ir.code.render}\`, ${ir.code.tokenReferences} token references, ${ir.stories.length} stories` : "no code evidence"} |`, "");
  L.push("## Props", "", "| Prop | Lever | Type | Default | Figma binding | Code |", "| --- | --- | --- | --- | --- | --- |");
  for (const p of ir.props) L.push(`| \`${p.name}\` | ${p.lever ? "yes" : "no"} | ${cell(p.type)}${p.enum ? ` (${p.enum.map((e) => `\`${e}\``).join(", ")})` : ""} | ${p.defaultSource === null ? "—" : `\`${cell(p.defaultSource)}\``} | ${fig(p.bindings.figma)} | \`${p.bindings.code.attr ? p.bindings.code.attr : p.bindings.code.prop}\`${p.bindings.code.extracted ? "" : " (not extracted)"} |`);
  L.push("");
  if (ir.states.length) {
    L.push("## States (runtime, not props)", "", "| State | Figma | Code | Notes |", "| --- | --- | --- | --- |");
    for (const s of ir.states) L.push(`| ${s.name} | ${fig(s.figma)} | ${cell(s.code.attr ? `${s.code.attr} = ${(s.code.values ?? []).join(" / ")}` : s.code.mechanism)} | ${cell(s.notes)} |`);
    L.push("");
  }
  L.push("## Anatomy and tokens", "");
  for (const part of ir.anatomy.parts) {
    const depth = part.path.split("/").length - 1;
    L.push(`${"  ".repeat(depth)}- **${part.name}** \`${part.selector}\`${part.figma ? ` ← Figma \`${part.figma}\`` : ""}${part.slot ? ` · slot \`${part.slot.name}\` accepts ${part.slot.accepts.map((a) => `\`${a}\``).join(", ")} (${part.slot.acceptsMode})` : ""}`);
    for (const [prop, t] of Object.entries(part.tokens)) {
      const detail = t.tokens.map((tok) => `\`${tok.cssVar}\`${tok.shipped ? ` = ${tok.value}${tok.dark ? ` / dark ${tok.dark}` : ""}${tok.sm ? ` / sm ${tok.sm}` : ""}` : " (not shipped)"}`).join(", ");
      L.push(`${"  ".repeat(depth + 1)}- ${prop}: ${t.raw ? `raw \`${t.value.slice(4)}\`` : detail}`);
    }
  }
  L.push("");
  if (ir.decisions.length) {
    L.push("## Decisions", "");
    for (const d of [...ir.decisions].sort((a, b) => (a.status === "open" ? -1 : 1) - (b.status === "open" ? -1 : 1))) L.push(`- ${d.status === "open" ? "⏳ **open**" : "✅ decided"} \`${d.id}\` (${d.owner ?? "unowned"}): ${d.question}${d.decision ? ` → ${d.decision}` : ""}${d.evidence ? ` _Evidence: ${d.evidence}_` : ""}`);
    L.push("");
  }
  if (ir.a11y) {
    L.push("## Accessibility", "", `WCAG 2.2 AA: ${(ir.a11y.wcag ?? []).map((w) => `\`${w}\``).join(", ") || "—"}`, "");
    for (const k of ir.a11y.keyboard ?? []) L.push(`- \`${k.key}\`: ${k.action}`);
    for (const n of ir.a11y.notes ?? []) L.push(`- ${n}`);
    L.push("");
  }
  if (ir.stories.length) L.push("## Stories", "", ...ir.stories.map((s) => `- \`${s.id}\` ${s.name}`), "");
  L.push("## Provenance", "", `- defs: ${ir.provenance.defs ?? "—"}`, `- code evidence: ${ir.provenance.codeEvidence ?? "—"}`, `- figma evidence: ${ir.provenance.figmaEvidence ?? "not published"}`, "");
  return L.join("\n");
}
